# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply',
            field=models.BooleanField(default=False, verbose_name=b'Is a reply?'),
        ),
    ]
